--表名：T_BaseInfo_Teacher; 
--别名：BT
--说明：教职工信息表 
CREATE TABLE T_BaseInfo_Teacher 
  ( 
     ID nvarchar(32) not null constraint DF_BT_ID default (replace(newid(),'-','')),
	nvcIsTeaching	nvarchar(1) not null ,
nvcTeachingType	nvarchar(20)null ,
nvcRoleType	nvarchar	(20)not null ,
intAuditorType int not null ,	
intGoodFlag	int not null ,	
nvcTeacherCode	nvarchar(8)not null ,
nvcLoginCode	nvarchar(4)not null ,
nvcPwd	nvarchar(50)not null ,
nvcName	nvarchar(20)not null ,
nvcSex	nvarchar(2)not null ,
nvcNationality	nvarchar(10)null ,
nvcBirth	nvarchar(20)not null ,
nvcPolitics	nvarchar	(20)not null ,
nvcCollege		nvarchar	(20)not null ,
nvcDepartment	nvarchar	(20),
nvcPhone	nvarchar	(20)null ,
nvcMail		nvarchar	(50)null ,
nvcGraduate	nvarchar	(50)null ,
nvcMajor	nvarchar	(50)null ,
nvcEducation	nvarchar	(20)not null ,
nvcDegree	nvarchar	(20)null ,
nvcJobTitle		nvarchar	(20)null ,
nvcJob		nvarchar	(20)null ,
nvcDiscipline	nvarchar	(50)null ,
nvcQualifyCode	nvarchar	(20)null ,
nvcMQualifyCode		nvarchar	(20)null ,
nvcPerStaffCode	nvarchar	(20)null ,
nvcLabMan	nvarchar(2)null ,
nvcEvaluation	nvarchar(1500)null ,
nvcTeacher	nvarchar(1500)null ,
nvcTeaPhoto	nvarchar(500)null ,

	constraint PK_BT_ID primary key(ID),
	constraint UQ_BT_nvcTeacherCode unique(nvcTeacherCode),
	constraint UQ_BT_nvcLoginCode unique(nvcLoginCode),
	constraint CK_BT_nvcIsTeaching check (nvcIsTeaching in ('0','1')),
	constraint CK_BT_intAuditorType check (intAuditorType in ('0','1','2')),
	constraint CK_BT_intGoodFlag check (intGoodFlag in ('0','1','2','3')),
  ); 