Ext.define('app.view.userinfo.InfoView', {
    alternateClassName: 'userInfo',
    extend: 'Ext.Container',
    xtype: 'userInfo',
    requires: ['ux.plugin.ConTpl'],
    config: {
        cls: 'info',
        title: '个人中心',
        plugins: 'conTpl',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        tpl: new Ext.XTemplate(
            '<tpl if="nvcStuNo">',
            '   <div class="bgdiv divline">',
            '       <div class="tc" style=font-size:15px>亲爱的<span class="orange"> {nvcStuName} </span>，<br/>&nbsp&nbsp&nbsp&nbsp欢迎使用安徽工业大学教辅系统</div>',
            '   </div>',
            '   <div class="pic"><img src="{nvcStuPhoto}"/></div>',
            '   <br/>',
            '   <p>学生信息：<br/><br/>',
            '   <tpl for=".">',
            '       &nbsp&nbsp姓&nbsp名：{nvcStuName}<br/>',
            '       &nbsp&nbsp学&nbsp号：{nvcStuNo}<br/>',
            '       &nbsp&nbsp班&nbsp级：{nvcClass}<br/>',
            '       &nbsp&nbsp学&nbsp院：{nvcCollege}<br/>',
            '   </tpl>',
            '<div class="bgdiv">',
            '   <br/>',
            '   <br/>',
            '</div>',
            '</tpl>',
            '<tpl if="nvcLoginCode">',
            '    <div class="bgdiv divline">',
            '       <div class="tc" style=font-size:15px>尊敬的<span class="orange"> {nvcName} </span>，<br/>&nbsp&nbsp&nbsp&nbsp欢迎使用安徽工业大学教辅系统</div>',
            '    </div>',
            '   <div class="pic"><img src="{nvcTeaPhoto}"/></div>',
            '   <br/>',
            '   <p>教师信息：<br/><br/>',
            '       <tpl for=".">',
            '           &nbsp&nbsp姓&nbsp名：{nvcName}<br/>',
            '           &nbsp&nbsp工&nbsp号：{nvcLoginCode}<br/>',
            '           &nbsp&nbsp学&nbsp院：{nvcCollege}<br/>',
            '           <tpl if="nvcRoleTypev==0">',
            '           &nbsp&nbsp职&nbsp能：教师<br/>',
            '           </tpl>',
            '       </tpl>',
            '       <div class="bgdiv">',
            '       <br/>',
            '       <br/>',
            '    </div>',
            '</tpl>'
        )
    }
});