Ext.define('BaseInfo_Student.model.StudentModel', {
    extend: 'Ext.data.Model',
    requires: [
        'Ext.data.Field'
    ],
    fields: [
        { name: 'ID'},
        { name: 'nvcStuNo'},
        { name: 'nvcStuName' },
         { name: 'nvcSex' },
         { name: 'nvcPwd'},
         { name: 'dtmBirth'},
        { name: 'nvcPolity'},
        { name: 'nvcNationality'},
        { name: 'nvcNative'},
         { name: 'nvcSource'},
        { name: 'nvcCollege'},
        { name: 'nvcFaculty'},
        { name: 'nvcMajor'},
        { name: 'nvcClass'},
        { name: 'intEducationAge'},
         { name: 'nvcEngGrade' },
         { name: 'nvcStuAge' },
         { name: 'nvcGradeStatus' },
         { name: 'nvcGrade' },
        { name: 'nvcDevelop'},
        { name: 'nvcMajorDir'},
        { name: 'dtmEntranceTime'},
        { name: 'nvcGraduateSch'},
         { name: 'nvcDormNo'},
        { name: 'nvcMail'},
        { name: 'nvcPhone'},
        { name: 'nvcAdmCode'},
        { name: 'nvcIdentity'},
        { name: 'nvcHMT'},
         { name: 'nvcHealth'},
        { name: 'nvcRegister'},
          { name: 'nvcFamilyAdd'},
         { name: 'nvcFamilyCode'},
        { name: 'nvcFamilyTel'},
         { name: 'nvcFather' },
         { name: 'nvcFaFirm' },
        { name: 'nvcFaFirmTel' },
         { name: 'nvcFaFirmCode' },
        { name: 'nvcMother'},
        { name: 'nvcMoFirm'},
         { name: 'nvcMoFirmTel'},
        { name: 'nvcMoFirmCode'},
        { name: 'nvcStuPhoto'}
    ]

});